# Generated by Django 4.2.13 on 2024-07-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "1051_workflow_assign_customers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="customer",
            new_name="customers",
        ),
    ]
